### ISSUE TITLE
Is the given matrix in .npy files a final multi-view adjacency matrix where weights are equal to one

### ISSUE THREAD

**Issue by anks12297** [gingasan/sit3#3]
Hi, thanks for sharing your great work!

After downloading data.zip, I could find only on matrix stored in .npy files. Whereas in the paper, three matrices are mentioned(AST matrix, control flow matrix and data dependency matrix) and their weighted sum is passed in attention layer. 

1. Is the given matrix in .npy files a final multi-view adjacency matrix where weights are equal to one?
2. If Yes, then not understanding why given .npy file matrix have boolean values as final matrix is weighted sum of 3 matrices as per paper so it should be real values?

Please correct me if my understanding is wrong.

**Comment by gingasan** [comment]
Thank you for your attention on my work. Your understand is correct. The given .npy files are the final multi-view adjacency matrices. Since the three are not overlapping, boolean value is ok. We suggest to use all one weights because empirically adjusting weights does not make improvement (we mention this in the paper). Of course float-type weights are ok with the model.

Best,
Hongqiu Wu

----- 原始邮件 -----
发件人: "anks12297" ***@***.***>
收件人: "gingasan/sit3" ***@***.***>
抄送: "Subscribed" ***@***.***>
发送时间: 星期一, 2021年 9 月 20日 下午 7:17:18
主题: [gingasan/sit3] Is there only one matrix in .npy file in folder adjacency but in paper multi-view matrix is the weighted sum of three matrices? (#3)

Hi, thanks for sharing your great work!

After downloading data.zip, I could find only on matrix stored in .npy files. Whereas in the paper, three matrices are mentioned(AST matrix, control flow matrix and data dependency matrix) and their weighted sum is passed in attention layer. 

1. Is the given matrix in .npy files a final multi-view adjacency matrix where weights are equal to one?
2. If Yes, then not understanding why given .npy file matrix have boolean values as final matrix is weighted sum of 3 matrices as per paper so it should be real values?

Please correct me if my understanding is wrong.

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/gingasan/sit3/issues/3

**Comment by anks12297** [comment]
Thank you for your prompt response!
